import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { useSession } from "next-auth/react";
import Provider from "@/components/Provider";
import Topbar from "@/components/Topbar";
import BottomBar from "@/components/BottomBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data: session } = useSession();

  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-2`}>
        <Provider session={session}>
          <Topbar />
          {children}
          <BottomBar />
        </Provider>
      </body>
    </html>
  );
}
